spring.application.name=journal App
spring.data.mongodb.uri=mongodb+srv://journalUser:MyStrongPassword123!@journalcluster.vbsvlgc.mongodb.net/journalDB?retryWrites=true&w=majority&appName=JournalCluster
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUGl